%% Get MATLAB browser info using javascript.

fig = uifigure;
panel = uipanel(fig, 'position', [1,1,fig.Position(3:4)]);
panel.Title = 'title';
panel.Position = [10,10, 200,200];

m1 = uimenu(fig,'Text','Show');
m1item = uimenu(m1,'Text','Data Types');
m2 = uimenu(fig,'Text','Edit');
m2item1 = uimenu(m2,'Text','Preferences');
m2item2 = uimenu(m2,'Text','Settings');

knob = uiknob(panel);

%[w,mN] = mlapptools.getWebElements(m);
[w,f] = mlapptools.getWebElements(fig);
[~,n] = mlapptools.getWebElements(panel);



%menuID =  sprintf('''[%s="%s"]''', mN.ID_attr, mN.ID_val); 
nodeID = sprintf('''[%s="%s"]''', n.ID_attr, n.ID_val);
figID = sprintf('''[%s="%s"]''', f.ID_attr, f.ID_val);


w.executeJS(sprintf(...
  [ ...
    'var menuParent = document.getElementById(%s);\n' ...
  ], ...
  '"dijit__Container_1"') ...
  );

w.executeJS(sprintf(...
  [ ...
    'var panel = document.querySelectorAll(%s)[0];\n', ...
    'panel.removeChild(panel.firstChild);\n' ...
  ], ...
  nodeID) ...
  );
w.executeJS( ...
  [ ...
    'var spanElement = document.createElement("span");', ...
    'spanElement.innerHTML = "some text here";', ...
    'spanElement.style.color = "blue";', ...
    'var newdiv = document.createElement("div");', ...
    'newdiv.style.textAlign = "right";', ...
    'newdiv.style.width = "100%";', ...
    'newdiv.appendChild(spanElement);', ...
    'menuParent.appendChild(newdiv);' ...
  ] ...
  );

%id="dijit__Container_1"